"""add google_budget_resource to campaigns

Revision ID: 7f032bcb0b9e
Revises: 603b78b45654
Create Date: 2025-12-28 14:46:53.241494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f032bcb0b9e'
down_revision = '603b78b45654'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_budget_resource', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_column('google_budget_resource')

    # ### end Alembic commands ###
